services:
  dashboard:
    image: ${DOCKER_REGISTRY-}blazorserver
    build:
      context: .
      dockerfile: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - UseInMemoryDatabase=false
      - DatabaseSettings__DBProvider=obe
      - DatabaseSettings__ConnectionString=User Id=DEV;Password=If(!password0);Data Source=(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1521)(host=adb.ap-sydney-1.oraclecloud.com))(connect_data=(service_name=g2cdd259f5e9502_serverpaneldatabase_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)));Connection Timeout=30;
      - AppConfigurationSettings__ApplicationUrl=https://TestingBlazor.server.com
      - SmtpClientOptions__Server=
      - SmtpClientOptions__Port=
      - SmtpClientOptions__User=
      - SmtpClientOptions__Password=
      - ASPNETCORE_URLS=https://+:443;http://+:80
      #- ASPNETCORE_Kestrel__Certificates__Default__Password=Password@123
      #- ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/CleanArchitecture.Blazor.Server.UI.pfx
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/root/.aspnet/https:ro
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - sqldb
    restart: on-failure

  sqldb:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      - "sa_password=password@123"
      - "accept_eula=y"
      - mssql_data_dir=/var/opt/mssql/data
      - mssql_log_dir=/var/opt/mssql/log
      - mssql_backup_dir=/var/opt/mssql/backup
    ports:
      - "1433:1433"
    volumes:
      - ${userprofile}\mssql_data:/var/opt/mssql/data
      - ${userprofile}\mssql_log:/var/opt/mssql/log
      - ${userprofile}\mssql_backup:/var/opt/mssql/backup
volumes:
  mssql_data:
  mssql_log:
  mssql_backup:
